Repository bounswe/bounswe2020group4, pull requests merged in 2020-05, with the labels that each got.

#73 COVID-19 TR Data branch merging.
  practice-app/backend/controllers/covid19.js
  practice-app/backend/package-lock.json
  practice-app/backend/package.json
  practice-app/backend/routes.js
  practice-app/backend/tests/covid19.spec.js
Labels: Coding, Task: Assignment

#80 Try/Usd rate endpoint.
  practice-app/backend/controllers/tryusd.js
  practice-app/backend/package-lock.json
  practice-app/backend/routes.js
  practice-app/backend/tests/tryusd.spec.js
Labels: Coding, Task: Assignment

#79 Covid News Endpoint
  practice-app/backend/controllers/covidNews.js
  practice-app/backend/routes.js
  practice-app/backend/tests/covidNews.spec.js
Labels: Coding, Task: Assignment

#86 Add basic layout for the website, and send website to server.
  practice-app/backend/routes.js
  practice-app/frontend/css/stylesheet.css
  practice-app/frontend/index.html
  practice-app/frontend/js/main.js
Labels: Coding, Effort: Medium, Group Work, Priority: Critical, Status: Needs Review

#88 Front end template v2
  practice-app/backend/controllers/covid19.js
  practice-app/backend/controllers/weatherNextDays.js
  practice-app/frontend/index.html
Labels: Coding, Priority: Critical, Task: Assignment

#92 Front end template / news
  practice-app/backend/controllers/covid19.js
  practice-app/frontend/index.html
Labels: Coding, Priority: Critical

#93 TRY-USD added
  practice-app/frontend/index.html
Labels: Coding, Priority: Critical

#95 add weather-important-cities scripts and containers
  practice-app/backend/controllers/weatherImportantCities.js
  practice-app/frontend/index.html
Labels: Coding, Priority: Critical, Status: Needs Review

#94 Add random-playlist and book-suggestion scripts and containers.
  practice-app/backend/controllers/suggestBook.js
  practice-app/frontend/index.html
Labels: Coding, Priority: Critical, Status: Needs Review

#101 Alignment of containers and explanations
  practice-app/backend/tests/nearestVendor.spec.js
  practice-app/backend/tests/suggestBook.spec.js
  practice-app/frontend/index.html
Labels: Coding, Priority: Critical

#100 Front end
  practice-app/backend/controllers/covid19.js
  practice-app/backend/controllers/nearestHospital.js
  practice-app/backend/controllers/suggestBook.js
  practice-app/backend/controllers/weatherImportantCities.js
  practice-app/backend/controllers/weatherNextDays.js
  practice-app/backend/routes.js
  practice-app/backend/tests/weatherNextDay.spec.js
  practice-app/frontend/css/stylesheet.css
  practice-app/frontend/index.html
  practice-app/frontend/js/main.js
  practice-app/frontend/js/scripts.js
Labels: Group Work, Priority: Critical, Status: Needs Review

#102 Dockerize
  practice-app/.dockerignore
  practice-app/Dockerfile
  practice-app/backend/.gitignore
  practice-app/backend/package.json
  practice-app/commands.sh
  practice-app/docker-compose.yml
  practice-app/package.json
Labels: Coding, Task: Assignment

#104 Documentation
  practice-app/documentation.md
Labels: Priority: Critical, Type: Documentation
